# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/main/python/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BLEScanner(object):
    def setupUi(self, BLEScanner):
        BLEScanner.setObjectName("BLEScanner")
        BLEScanner.resize(893, 329)
        self.centralwidget = QtWidgets.QWidget(BLEScanner)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uuidLabel = QtWidgets.QLabel(self.centralwidget)
        self.uuidLabel.setObjectName("uuidLabel")
        self.horizontalLayout.addWidget(self.uuidLabel)
        self.uudiLine = QtWidgets.QLineEdit(self.centralwidget)
        self.uudiLine.setObjectName("uudiLine")
        self.horizontalLayout.addWidget(self.uudiLine)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBox.setObjectName("textBox")
        self.verticalLayout.addWidget(self.textBox)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_2.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_2.addWidget(self.stopButton)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_2.addWidget(self.clearButton)
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout_2.addWidget(self.exitButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        BLEScanner.setCentralWidget(self.centralwidget)

        self.retranslateUi(BLEScanner)
        QtCore.QMetaObject.connectSlotsByName(BLEScanner)

    def retranslateUi(self, BLEScanner):
        _translate = QtCore.QCoreApplication.translate
        BLEScanner.setWindowTitle(_translate("BLEScanner", "BLEScanner"))
        self.uuidLabel.setText(_translate("BLEScanner", "UUID"))
        self.uudiLine.setText(_translate("BLEScanner", ""))
        self.label.setText(_translate("BLEScanner", "Scan Stopped"))
        self.label.setStyleSheet("color : red;")
        self.startButton.setText(_translate("BLEScanner", "Start"))
        self.stopButton.setText(_translate("BLEScanner", "Stop"))
        self.clearButton.setText(_translate("BLEScanner", "Clear"))
        self.exitButton.setText(_translate("BLEScanner", "Exit"))
